import { API_URL, get, post } from '../api.js';
import { badge, date, esc, number } from '../format.js?v=20260824-2';
import { recordModal } from '../quick_create.js';
import { state } from '../state.js';
import { pageHeader, toast } from '../ui.js?v=20260821-19';

const table=(label,heads,rows)=>`<div class="table-wrap"><table class="data-table" aria-label="${esc(label)}"><thead><tr>${heads.map(x=>`<th scope="col">${x}</th>`).join('')}</tr></thead><tbody>${rows.join('')||`<tr><td colspan="${heads.length}" class="ops-empty-cell">Sem registos.</td></tr>`}</tbody></table></div>`;
const role=()=>state.companies.find(row=>Number(row.id)===Number(state.companyId))?.role||'';
const can=(roles)=>roles.includes(role());
const rowSearch=(...values)=>esc(values.filter(Boolean).join(' ').toLowerCase());

function rejectedReason(result){return result.status==='rejected'&&result.reason?.status!==403?(result.reason?.message||'Não foi possível carregar esta área.'):'';}
function sectionError(title,message){return message?`<section class="ops-panel-card ops-error"><div><span aria-hidden="true">!</span></div><div><h2>${esc(title)}</h2><p>${esc(message)}</p></div></section>`:'';}
function filterKey(){return `tf_ops_filters_${state.companyId}`;}
function readFilters(){try{const value=JSON.parse(localStorage.getItem(filterKey())||'{}');return value&&typeof value==='object'?value:{}}catch{return {}}}
function saveFilters(value){try{localStorage.setItem(filterKey(),JSON.stringify(value))}catch{}}
function openState(closed){return closed?'closed':'open';}
function loadingShell(){return `<div class="ops-shell" aria-busy="true"><section class="ops-command skeleton-card skeleton"></section><div class="ops-metrics">${Array.from({length:5},()=>'<article class="skeleton-card skeleton"></article>').join('')}</div><section class="ops-panel-card ops-loading-panel"><div class="loading">A preparar a central operacional…</div></section></div>`;}

export async function render(container){
  const base=`/operations-control/${state.companyId}`;
  container.innerHTML=pageHeader('Fluxo operacional integrado','Caixas e lotes, retrabalho, devoluções, compras sugeridas e leitura de códigos.','<a class="btn" href="#/tracking">OF e rastreabilidade</a><a class="btn primary" href="#/shipping">Expedição</a>')+loadingShell();
  const results=await Promise.allSettled([get(`${base}/finished-goods`),get(`${base}/rework`),get(`${base}/procurement`),get(`${base}/claims`),get(`${base}/return-options`),get(`${base}/notifications`)]);
  const [stockResult,reworkResult,procurementResult,claimResult,returnResult,noteResult]=results;
  const stock=stockResult.status==='fulfilled'?stockResult.value:null;
  const reworks=reworkResult.status==='fulfilled'?reworkResult.value:null;
  const procurement=procurementResult.status==='fulfilled'?procurementResult.value:null;
  const claims=claimResult.status==='fulfilled'?claimResult.value:null;
  const returns=returnResult.status==='fulfilled'?returnResult.value:null;
  const notes=noteResult.status==='fulfilled'?noteResult.value:null;
  const stockRows=stock?.items||[];
  const reworkRows=reworks||[];
  const procurementRows=procurement||[];
  const claimRows=claims||[];
  const returnRows=returns||[];
  const noteRows=notes||[];
  const unreadRows=noteRows.filter(x=>x.status!=='read');
  const buys=procurementRows.filter(x=>x.status==='suggested'&&x.suggested_quantity>0);
  const tabs=[['overview','Visão geral',unreadRows.length+buys.length+reworkRows.filter(x=>!['completed','cancelled'].includes(x.status)).length]];
  if(stock)tabs.push(['stock','Produto acabado',stockRows.length]);
  if(reworks)tabs.push(['rework','Retrabalho',reworkRows.filter(x=>!['completed','cancelled'].includes(x.status)).length]);
  if(procurement)tabs.push(['procurement','Compras',buys.length]);
  if(claims)tabs.push(['claims','Pós-venda',claimRows.filter(x=>x.status!=='closed').length]);
  if(notes)tabs.push(['history','Histórico',noteRows.length]);
  const stored=readFilters();
  const active=tabs.some(([id])=>id===stored.active)?stored.active:'overview';
  const activeReworks=reworkRows.filter(x=>!['completed','cancelled'].includes(x.status));
  const openClaims=claimRows.filter(x=>x.status!=='closed');
  const priorityItems=[
    ...activeReworks.slice(0,3).map(x=>({tab:'rework',tone:'warning',title:`Retrabalho ${x.reference}`,detail:`${number(Math.max(0,x.quantity-x.completed_quantity-x.scrap_quantity))} unidades por tratar`})),
    ...buys.slice(0,3).map(x=>({tab:'procurement',tone:'warning',title:`Comprar ${x.material_code||x.material_name}`,detail:`Faltam ${number(x.suggested_quantity)} unidades`})),
    ...openClaims.slice(0,3).map(x=>({tab:'claims',tone:'danger',title:`Reclamação ${x.claim_no}`,detail:`${x.customer||x.order_no||'Cliente'} · ${number(x.quantity)} unidades`})),
    ...unreadRows.slice(0,3).map(x=>({tab:'history',tone:x.severity==='critical'?'danger':'info',title:x.title||'Aviso operacional',detail:x.detail||'Requer atenção'})),
  ].slice(0,7);
  const contextActions={overview:['Abrir expedição','#/shipping'],stock:['Registar embalagem','#/embalagem'],rework:['Abrir qualidade','#/quality'],procurement:['Ver compras e stock','#/inventory'],claims:['Abrir expedições','#/shipping'],history:['Abrir torre de controlo','#/control-tower']};
  const context=contextActions[active]||contextActions.overview;
  const parts=[
    pageHeader('Fluxo operacional integrado','Caixas e lotes, retrabalho, devoluções, compras sugeridas e leitura de códigos.','<a class="btn" href="#/tracking">OF e rastreabilidade</a><a class="btn primary" href="#/shipping">Expedição</a>'),
    `<div class="ops-shell">
      <section class="ops-command" aria-label="Leitor de códigos"><div><span class="ops-eyebrow">Localização imediata</span><h2>Ler lote, caixa ou retrabalho</h2><p>Use um leitor USB ou introduza o código manualmente.</p></div><form data-scan class="ops-scan"><label class="sr-only" for="ops-code">Código</label><input id="ops-code" name="code" placeholder="Ex.: FG-1-24-0001" autocomplete="off" required><button class="btn primary">Localizar</button></form><div data-scan-result class="ops-scan-result" role="status" aria-live="polite"></div></section>
      <div class="ops-metrics">
        <article><span>Produto disponível</span><strong>${number(stock?.available_quantity||0)}</strong><small>unidades físicas</small></article>
        <article><span>Retrabalhos ativos</span><strong>${reworkRows.filter(x=>!['completed','cancelled'].includes(x.status)).length}</strong><small>a concluir</small></article>
        <article><span>Compras sugeridas</span><strong>${buys.length}</strong><small>por falta confirmada</small></article>
        <article><span>Pós-venda aberto</span><strong>${claimRows.filter(x=>x.status!=='closed').length}</strong><small>processos</small></article>
        <article><span>Avisos novos</span><strong>${unreadRows.length}</strong><small>requerem atenção</small></article>
      </div>
      ${tabs.length?`<div class="ops-toolbar"><nav class="ops-tabs" aria-label="Áreas operacionais" role="tablist">${tabs.map(([id,label,count])=>`<button class="ops-tab ${id===active?'active':''}" type="button" role="tab" data-ops-tab="${id}" aria-controls="ops-panel-${id}" aria-selected="${id===active}">${esc(label)}<span>${count}</span></button>`).join('')}</nav><div class="ops-filter-bar"><label class="ops-search"><span data-icon="search" aria-hidden="true"></span><input type="search" data-ops-search value="${esc(stored.query||'')}" placeholder="Filtrar a área atual…" aria-label="Filtrar registos"></label><label class="ops-status-filter"><span class="sr-only">Estado</span><select data-ops-status aria-label="Filtrar por estado"><option value="all">Todos os estados</option><option value="open" ${stored.status==='open'?'selected':''}>Abertos / disponíveis</option><option value="closed" ${stored.status==='closed'?'selected':''}>Concluídos / fechados</option><option value="unread" ${stored.status==='unread'?'selected':''}>Não lidos</option></select></label><a class="btn primary ops-context-action" data-ops-context href="${context[1]}">${context[0]}</a></div></div>`:''}
      <div class="ops-panels">
        <section class="ops-panel-card ops-overview" id="ops-panel-overview" role="tabpanel" data-ops-panel="overview" ${active==='overview'?'':'hidden'}><header><div><span class="ops-eyebrow">Decidir primeiro</span><h2>Visão geral operacional</h2><p>Exceções e próximos passos sem percorrer todas as tabelas.</p></div></header><div class="ops-overview-grid"><div class="ops-priority-list"><h3>Prioridades</h3>${priorityItems.length?priorityItems.map(item=>`<button type="button" class="ops-priority ${item.tone}" data-open-ops="${item.tab}"><span data-icon="${item.tone==='danger'?'warning':'forward'}" aria-hidden="true"></span><span><b>${esc(item.title)}</b><small>${esc(item.detail)}</small></span><span data-icon="forward" aria-hidden="true"></span></button>`).join(''):'<div class="ui-state success"><span data-icon="check" aria-hidden="true"></span><strong>Operação controlada</strong><span>Não existem exceções urgentes neste momento.</span></div>'}</div><aside class="ops-quick-actions"><h3>Ações frequentes</h3><a href="#/embalagem"><span data-icon="box"></span><b>Registar embalagem</b><small>Criar caixas com lote e variante.</small></a><a href="#/shipping"><span data-icon="truck"></span><b>Preparar expedição</b><small>Expedir a encomenda numa ou várias partes.</small></a><a href="#/quality"><span data-icon="quality"></span><b>Controlar qualidade</b><small>Inspecionar, retrabalhar ou dar destino.</small></a></aside></div></section>
        ${stock?`<section class="ops-panel-card" id="ops-panel-stock" role="tabpanel" data-ops-panel="stock" ${active==='stock'?'':'hidden'}><header><div><span class="ops-eyebrow">Stock rastreável</span><h2>Produto acabado físico</h2><p>FIFO por caixa, variante, lote e armazém.</p></div><a class="btn" href="#/embalagem">Registar embalagem</a></header>${table('Produto acabado',['Caixa / código','OF','Variante','Inicial','Disponível','Expedido','Local','Estado',''],stockRows.map(x=>`<tr data-ops-row data-state="${openState(Number(x.available_quantity)<=0)}" data-status="${esc(x.status)}" data-search="${rowSearch(x.package_code,x.barcode,x.order_no,x.variant,x.warehouse,x.location,x.status)}"><td><b>${esc(x.package_code)}</b><small class="table-subline">${esc(x.barcode)}</small></td><td>${esc(x.order_no)}</td><td>${esc(x.variant||'—')}</td><td>${number(x.initial_quantity)}</td><td><b>${number(x.available_quantity)}</b></td><td>${number(x.shipped_quantity)}</td><td>${esc(x.warehouse||x.location||'—')}</td><td>${badge(x.status)}</td><td><button class="btn small" data-label="finished-goods,${x.id}">Etiqueta</button></td></tr>`))}</section>`:sectionError('Produto acabado',rejectedReason(stockResult))}
        ${reworks?`<section class="ops-panel-card" id="ops-panel-rework" role="tabpanel" data-ops-panel="rework" ${active==='rework'?'':'hidden'}><header><div><span class="ops-eyebrow">Circuito de qualidade</span><h2>Retrabalho</h2><p>Qualidade → correção → reinspeção.</p></div></header>${table('Retrabalhos',['Referência','Qtd.','Recuperada','Desperdício','Por tratar','Estado',''],reworkRows.map(x=>`<tr data-ops-row data-state="${openState(['completed','cancelled'].includes(x.status))}" data-status="${esc(x.status)}" data-search="${rowSearch(x.reference,x.reason,x.status)}"><td><b>${esc(x.reference)}</b><small class="table-subline">${esc(x.reason||'')}</small></td><td>${number(x.quantity)}</td><td>${number(x.completed_quantity)}</td><td>${number(x.scrap_quantity)}</td><td><b>${number(Math.max(0,x.quantity-x.completed_quantity-x.scrap_quantity))}</b></td><td>${badge(x.status)}</td><td>${can(['admin','manager','quality','supervisor'])&&!['completed','cancelled'].includes(x.status)?`<button class="btn small primary" data-rework="${x.id}">Registar resultado</button>`:''}<button class="btn small" data-label="rework,${x.id}">Etiqueta</button></td></tr>`))}</section>`:sectionError('Retrabalho',rejectedReason(reworkResult))}
        ${procurement?`<section class="ops-panel-card" id="ops-panel-procurement" role="tabpanel" data-ops-panel="procurement" ${active==='procurement'?'':'hidden'}><header><div><span class="ops-eyebrow">Compra por exceção</span><h2>Aprovisionamento sugerido</h2><p>Apenas faltas confirmadas e ainda não cobertas.</p></div>${can(['admin','manager','warehouse'])?`<button class="btn primary" data-convert ${buys.length?'':'disabled'}>Criar OC selecionadas</button>`:''}</header>${table('Aprovisionamento',['','Material','Fornecedor','OF','Necessário','Disponível','A comprar','Data','Estado'],procurementRows.map(x=>`<tr data-ops-row data-state="${openState(x.status!=='suggested')}" data-status="${esc(x.status)}" data-search="${rowSearch(x.material_code,x.material_name,x.supplier,x.order_no,x.status)}"><td>${can(['admin','manager','warehouse'])?`<input type="checkbox" aria-label="Selecionar ${esc(x.material_code||x.material_id)}" data-buy="${x.id}" ${x.status==='suggested'&&x.suggested_quantity>0?'checked':'disabled'}>`:''}</td><td><b>${esc(x.material_code||'#'+x.material_id)}</b><small class="table-subline">${esc(x.material_name||'')}</small></td><td>${esc(x.supplier||'Por definir')}</td><td>${esc(x.order_no||'#'+x.production_order_id)}</td><td>${number(x.required_quantity)}</td><td>${number(x.available_quantity)}</td><td><b>${number(x.suggested_quantity)}</b></td><td>${date(x.needed_by)}</td><td>${badge(x.status)}</td></tr>`))}</section>`:sectionError('Aprovisionamento',rejectedReason(procurementResult))}
        ${claims?`<section class="ops-panel-card" id="ops-panel-claims" role="tabpanel" data-ops-panel="claims" ${active==='claims'?'':'hidden'}><header><div><span class="ops-eyebrow">Cliente e devolução</span><h2>Pós-venda</h2><p>Reclamações ligadas à expedição, caixa e lote originais.</p></div>${can(['admin','manager','commercial','warehouse','quality'])?`<button class="btn primary" data-new-claim ${returnRows.length?'':'disabled'}>Nova reclamação</button>`:''}</header>${table('Pós-venda',['Processo','Cliente / encomenda','Expedição','Tipo','Qtd.','Motivo','Estado',''],claimRows.map(x=>`<tr data-ops-row data-state="${openState(x.status==='closed')}" data-status="${esc(x.status)}" data-search="${rowSearch(x.claim_no,x.customer,x.order_no,x.shipment_no,x.claim_type,x.reason,x.status)}"><td><b>${esc(x.claim_no)}</b></td><td><b>${esc(x.customer||'—')}</b><small class="table-subline">${esc(x.order_no||'#'+x.sales_order_id)}</small></td><td>${esc(x.shipment_no||'—')}</td><td>${esc(x.claim_type)}</td><td>${number(x.quantity)}</td><td>${esc(x.reason||'—')}</td><td>${badge(x.status)}</td><td>${can(['admin','manager','warehouse','quality'])?x.lines.filter(y=>y.status==='received').map(y=>`<button class="btn small" data-return="${y.id}">Dar destino (${number(y.quantity)})</button>`).join(''):''}${can(['admin','manager','commercial','quality'])&&x.status!=='closed'?`<button class="btn small" data-close="${x.id}">Fechar</button>`:''}</td></tr>`))}</section>`:sectionError('Pós-venda',rejectedReason(claimResult))}
        ${notes?`<section class="ops-panel-card" id="ops-panel-history" role="tabpanel" data-ops-panel="history" ${active==='history'?'':'hidden'}><header><div><span class="ops-eyebrow">Histórico e notificações</span><h2>Atividade operacional</h2><p>Avisos lidos e pendentes, ordenados do mais recente para o mais antigo.</p></div></header>${table('Histórico operacional',['Estado','Prioridade','Aviso','Detalhe','Data',''],noteRows.map(x=>`<tr data-ops-row data-state="${x.status==='read'?'closed':'unread'}" data-status="${esc(x.status)}" data-search="${rowSearch(x.severity,x.title,x.detail,x.status)}"><td>${badge(x.status==='read'?'Lida':'Nova')}</td><td>${badge(x.severity||'info')}</td><td><b>${esc(x.title||'Aviso operacional')}</b></td><td>${esc(x.detail||'—')}</td><td>${date(x.created_at||x.sent_at)}</td><td>${x.action_route?`<a class="btn small" href="#/${esc(x.action_route)}">Abrir</a>`:''}${x.status!=='read'?`<button class="btn small" data-read-note="${x.id}">Marcar lida</button>`:''}</td></tr>`))}</section>`:sectionError('Histórico',rejectedReason(noteResult))}
      </div>
    </div>`,
  ];
  container.innerHTML=parts.join('');
  bind(container,{base,reworks:reworkRows,returns:returnRows});
}

function bind(container,data){
  const contextActions={overview:['Abrir expedição','#/shipping'],stock:['Registar embalagem','#/embalagem'],rework:['Abrir qualidade','#/quality'],procurement:['Ver compras e stock','#/inventory'],claims:['Abrir expedições','#/shipping'],history:['Abrir torre de controlo','#/control-tower']};
  let active=container.querySelector('[data-ops-tab].active')?.dataset.opsTab||'overview';
  const applyFilters=()=>{const query=container.querySelector('[data-ops-search]')?.value.trim().toLowerCase()||'';const status=container.querySelector('[data-ops-status]')?.value||'all';const panel=container.querySelector(`[data-ops-panel="${active}"]`);panel?.querySelectorAll('[data-ops-row]').forEach(row=>{const matchesQuery=!query||row.dataset.search.includes(query);const matchesState=status==='all'||row.dataset.state===status;row.hidden=!(matchesQuery&&matchesState)});saveFilters({active,query,status})};
  const selectTab=id=>{active=id;container.querySelectorAll('[data-ops-tab]').forEach(button=>{const on=button.dataset.opsTab===id;button.classList.toggle('active',on);button.setAttribute('aria-selected',String(on));button.tabIndex=on?0:-1});container.querySelectorAll('[data-ops-panel]').forEach(panel=>{panel.hidden=panel.dataset.opsPanel!==id});const context=container.querySelector('[data-ops-context]');const action=contextActions[id]||contextActions.overview;if(context){context.textContent=action[0];context.href=action[1]}applyFilters()};
  container.querySelectorAll('[data-ops-tab]').forEach(button=>button.addEventListener('click',()=>selectTab(button.dataset.opsTab)));
  container.querySelectorAll('[data-open-ops]').forEach(button=>button.addEventListener('click',()=>selectTab(button.dataset.openOps)));
  container.querySelector('[data-ops-search]')?.addEventListener('input',applyFilters);
  container.querySelector('[data-ops-status]')?.addEventListener('change',applyFilters);
  container.querySelector('.ops-tabs')?.addEventListener('keydown',event=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;event.preventDefault();const tabs=[...container.querySelectorAll('[data-ops-tab]')];let index=tabs.findIndex(tab=>tab.dataset.opsTab===active);if(event.key==='Home')index=0;else if(event.key==='End')index=tabs.length-1;else index=(index+(event.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;selectTab(tabs[index].dataset.opsTab);tabs[index].focus()});
  container.querySelector('[data-scan]')?.addEventListener('submit',async e=>{e.preventDefault();try{const code=new FormData(e.currentTarget).get('code');const r=await get(`${data.base}/scan/${encodeURIComponent(code)}`);const x=r.record||{};container.querySelector('[data-scan-result]').innerHTML=`<b>${esc(r.kind)}</b> · ${esc(x.batch_no||x.package_code||x.reference||code)} · ${badge(x.status||r.next_action)}`}catch(error){toast(error.message,'error')}});
  container.querySelectorAll('[data-label]').forEach(b=>b.addEventListener('click',()=>downloadLabel(...b.dataset.label.split(','))));
  container.querySelectorAll('[data-rework]').forEach(b=>b.addEventListener('click',()=>completeRework(container,data,b)));
  container.querySelector('[data-convert]')?.addEventListener('click',async()=>{const suggestion_ids=[...container.querySelectorAll('[data-buy]:checked')].map(x=>Number(x.dataset.buy));if(!suggestion_ids.length)return toast('Selecione uma sugestão.','error');try{await post(`${data.base}/procurement/convert`,{suggestion_ids});toast('Ordens de compra criadas em rascunho.');render(container)}catch(error){toast(error.message,'error')}});
  container.querySelector('[data-new-claim]')?.addEventListener('click',()=>newClaim(container,data));
  container.querySelectorAll('[data-return]').forEach(b=>b.addEventListener('click',()=>returnDestination(container,data,b)));
  container.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>recordModal({title:'Fechar reclamação',fields:[{key:'resolution',label:'Resolução',type:'textarea',required:true,full:true}],save:p=>post(`${data.base}/claims/${b.dataset.close}/close`,p),onSaved:()=>render(container)})));
  container.querySelectorAll('[data-read-note]').forEach(b=>b.addEventListener('click',async()=>{try{await post(`${data.base}/notifications/${b.dataset.readNote}/read`,{});render(container)}catch(error){toast(error.message,'error')}}));
  selectTab(active);
}

function completeRework(container,data,button){const row=data.reworks.find(x=>x.id===Number(button.dataset.rework));recordModal({title:`Resultado · ${row.reference}`,values:{completed_quantity:Math.max(0,row.quantity-row.completed_quantity-row.scrap_quantity),scrap_quantity:0},fields:[{key:'completed_quantity',label:'Recuperadas',type:'number',required:true},{key:'scrap_quantity',label:'Desperdício',type:'number',default:0},{key:'labor_cost',label:'Mão de obra (€)',type:'number',default:0,section:'Custo real'},{key:'material_cost',label:'Materiais (€)',type:'number',default:0,section:'Custo real'},{key:'energy_cost',label:'Energia (€)',type:'number',default:0,section:'Custo real'},{key:'notes',label:'Resolução',type:'textarea',full:true}],save:p=>post(`${data.base}/rework/${row.id}/complete`,p),onSaved:()=>render(container)});}

function newClaim(container,data){const opts=data.returns.map((x,i)=>({value:i,label:`${x.order_no} · ${x.shipment_no} · ${x.package_code||'sem caixa'} · máx. ${number(x.quantity)}`}));recordModal({title:'Nova reclamação / devolução',values:{option_index:0,claim_type:'quality',severity:'major',quantity:data.returns[0]?.quantity||0},fields:[{key:'option_index',label:'Expedição e caixa',type:'select',options:opts,required:true},{key:'claim_type',label:'Tipo',type:'select',options:['quality','quantity','delivery','commercial']},{key:'severity',label:'Gravidade',type:'select',options:['minor','major','critical']},{key:'quantity',label:'Quantidade devolvida',type:'number',required:true},{key:'reason',label:'Motivo',type:'textarea',required:true,full:true}],save:p=>{const x=data.returns[Number(p.option_index)];return post(`${data.base}/claims`,{sales_order_id:x.sales_order_id,shipment_id:x.shipment_id,claim_type:p.claim_type,severity:p.severity,reason:p.reason,lines:[{shipment_line_id:x.shipment_line_id,shipment_allocation_id:x.shipment_allocation_id,quantity:Number(p.quantity)}]})},onSaved:()=>render(container)});}

function returnDestination(container,data,button){recordModal({title:'Destino da devolução',values:{disposition:'restock'},fields:[{key:'disposition',label:'Destino',type:'select',required:true,options:[{value:'restock',label:'Reentrada em produto acabado'},{value:'rework',label:'Retrabalho'},{value:'second_quality',label:'Segunda qualidade / quarentena'},{value:'scrap',label:'Desperdício'}]}],save:p=>post(`${data.base}/returns/${button.dataset.return}/disposition`,p),onSaved:()=>render(container)});}

async function downloadLabel(kind,id){try{const response=await fetch(`${API_URL}/operations-control/${state.companyId}/labels/${kind}/${id}.svg`,{headers:{Authorization:`Bearer ${localStorage.getItem('tf_token')}`}});if(!response.ok)throw new Error('Não foi possível gerar a etiqueta');const url=URL.createObjectURL(await response.blob());const a=document.createElement('a');a.href=url;a.download=`etiqueta-${id}.svg`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(error){toast(error.message,'error')}}
