import { crudList, get } from '../api.js';
import { esc, number, percent } from '../format.js?v=20260819-5';
import { state } from '../state.js';
import { pageHeader, toast } from '../ui.js?v=20260820-5';

const DAY = 86400000;

export async function render(container) {
  const [capacity, assignments, machines, lines, orders] = await Promise.all([
    get(`/production/${state.companyId}/capacity`), crudList('work-assignments',state.companyId,'limit=2000'),
    crudList('machines',state.companyId,'limit=2000'), crudList('production-lines',state.companyId,'limit=2000'),
    crudList('production-orders',state.companyId,'limit=2000'),
  ]);
  let mode='finite', rule='priority', horizon=7, search='';
  const today=startDay(new Date());
  const orderMap=Object.fromEntries(orders.map(row=>[row.id,row]));
  const lineMap=Object.fromEntries(lines.map(row=>[row.id,row]));
  const relevant=assignments.filter(row=>!['completed','cancelled'].includes(row.status));
  container.innerHTML=pageHeader('MCM + MQM · Capacidade e sequenciação','Planeamento gráfico integrado, da capacidade da fábrica à fila de cada máquina.','<a class="btn" href="#/machines">Ver planta da fábrica</a><a class="btn primary" href="#/orders">Gerir ordens</a>')+`
    <div class="mcm-command"><div class="mcm-mode"><span>Modo de cálculo</span><button class="active" data-mcm-mode="finite">Capacidade finita<small>Respeita limites e disponibilidade</small></button><button data-mcm-mode="infinite">Capacidade infinita<small>Prioriza a data de entrega</small></button></div><div class="mcm-controls"><label>Regra de sequenciação<select data-mcm-rule><option value="priority">Prioridade da ordem</option><option value="delivery">Data de entrega</option><option value="shortest">Operação mais curta</option><option value="value">Maior quantidade</option></select></label><label>Horizonte<select data-mcm-horizon><option value="7">7 dias</option><option value="14">14 dias</option><option value="30">30 dias</option></select></label><button class="btn primary" data-mcm-calculate>Otimizar plano</button></div></div><div data-mcm-content></div>`;
  const content=container.querySelector('[data-mcm-content]');

  const draw=()=>{
    const schedule=buildSchedule({assignments:relevant,machines,orderMap,lineMap,mode,rule,horizon,today});
    const total=schedule.reduce((sum,row)=>sum+row.minutes,0), overloaded=schedule.filter(row=>row.overload).length, late=schedule.filter(row=>row.late).length;
    const unavailable=schedule.filter(row=>row.machine&&['maintenance','stopped'].includes(row.machine.status)).length;
    const utilization=machines.length?Math.min(100,Math.round(total/(machines.length*horizon*480)*100)):0;
    content.innerHTML=`<div class="mcm-kpis"><article><span>Utilização prevista</span><strong>${utilization}%</strong><small>${number(total)} minutos planeados</small><i class="ok"></i></article><article><span>Estrangulamentos</span><strong>${overloaded}</strong><small>${overloaded?'recursos acima da capacidade':'capacidade equilibrada'}</small><i class="${overloaded?'bad':'ok'}"></i></article><article><span>Ordens em risco</span><strong>${late}</strong><small>${late?'entrega requer atenção':'sem atrasos previstos'}</small><i class="${late?'warn':'ok'}"></i></article><article><span>Conflitos de recursos</span><strong>${unavailable}</strong><small>${unavailable?'máquina indisponível':'recursos compatíveis'}</small><i class="${unavailable?'bad':'info'}"></i></article></div>
      <div class="mcm-alerts">${alerts(capacity,schedule)}</div>
      <section class="mcm-board card"><header class="mcm-board-head"><div><h2>MQM · Fila gráfica por máquina</h2><p>Arraste uma tarefa para simular outra data; use as ações para dividir ou reagrupar.</p></div><div class="actions"><label class="mcm-find">⌕ <input data-mcm-search value="${esc(search)}" placeholder="Máquina ou ordem…"></label><button class="btn" data-mcm-today>Hoje</button></div></header>${renderGantt(schedule,machines,horizon,today)}</section>
      <div class="mcm-bottom"><section class="card"><div class="card-header"><h2>MCM · Carga por centro produtivo</h2><span>Capacidade diária</span></div><div class="mcm-load-list">${capacity.map(row=>`<div class="mcm-load-row"><div><b>${esc(row.name)}</b><small>${row.assignments} tarefas · ${number(row.available_minutes)} min/dia</small></div><strong class="${row.load_pct>100?'danger':row.load_pct>85?'warning':''}">${percent(row.load_pct)}</strong><div class="mcm-load-track"><i class="${row.load_pct>100?'danger':row.load_pct>85?'warning':''}" style="width:${Math.min(100,row.load_pct)}%"></i></div></div>`).join('')}</div></section><section class="card mcm-scenarios"><div class="card-header"><h2>Cenários hipotéticos</h2><span>Impacto estimado</span></div>${scenarioCards(utilization,late,overloaded)}</section></div>`;
    bind(schedule);
  };
  container.querySelectorAll('[data-mcm-mode]').forEach(button=>button.addEventListener('click',()=>{container.querySelectorAll('[data-mcm-mode]').forEach(item=>item.classList.toggle('active',item===button));mode=button.dataset.mcmMode;draw();}));
  container.querySelector('[data-mcm-rule]').addEventListener('change',event=>rule=event.target.value);
  container.querySelector('[data-mcm-horizon]').addEventListener('change',event=>horizon=Number(event.target.value));
  container.querySelector('[data-mcm-calculate]').addEventListener('click',()=>{draw();toast('Plano otimizado com as regras selecionadas.');});
  function bind(schedule){
    content.querySelector('[data-mcm-search]').addEventListener('input',event=>{search=event.target.value.toLowerCase();content.querySelectorAll('.mcm-resource-row').forEach(row=>row.hidden=!row.dataset.search.includes(search));});
    content.querySelector('[data-mcm-today]').addEventListener('click',()=>content.querySelector('.mcm-timeline')?.scrollTo({left:0,behavior:'smooth'}));
    content.querySelectorAll('.mcm-task').forEach(task=>{task.addEventListener('pointerdown',event=>dragTask(event,task));task.addEventListener('click',event=>{if(event.detail===0)return;showTaskActions(task,schedule.find(row=>row.id===Number(task.dataset.task)));});});
    content.querySelectorAll('[data-scenario]').forEach(button=>button.addEventListener('click',()=>{rule=button.dataset.scenario;container.querySelector('[data-mcm-rule]').value=rule;draw();toast('Cenário aplicado ao plano.');}));
  }
  function dragTask(event,task){event.preventDefault();const startX=event.clientX,initial=parseFloat(task.style.left);task.setPointerCapture(event.pointerId);task.classList.add('dragging');const move=e=>{const width=task.parentElement.getBoundingClientRect().width;task.style.left=`${Math.max(0,Math.min(96,initial+(e.clientX-startX)/width*100))}%`;};const up=()=>{task.classList.remove('dragging');task.removeEventListener('pointermove',move);toast('Alternativa simulada. Use “Otimizar plano” para recalcular.');};task.addEventListener('pointermove',move);task.addEventListener('pointerup',up,{once:true});}
  function showTaskActions(task,row){content.querySelectorAll('.mcm-task-menu').forEach(item=>item.remove());const menu=document.createElement('div');menu.className='mcm-task-menu';menu.innerHTML=`<b>${esc(row?.order?.order_no||'Tarefa')}</b><span>${number(row?.minutes||0)} min · ${number(row?.planned_quantity||0)} unidades</span><button data-task-action="split">Dividir tarefa</button><button data-task-action="group">Agrupar na máquina</button><button data-task-action="priority">Marcar como prioritária</button>`;task.parentElement.appendChild(menu);menu.querySelectorAll('button').forEach(button=>button.addEventListener('click',()=>{menu.remove();toast(button.dataset.taskAction==='split'?'Tarefa dividida na simulação.':button.dataset.taskAction==='group'?'Tarefas agrupadas na simulação.':'Prioridade atualizada na simulação.');}));setTimeout(()=>document.addEventListener('click',()=>menu.remove(),{once:true}),0);}
  draw();
}

function buildSchedule({assignments,machines,orderMap,lineMap,mode,rule,horizon,today}){
  const machineMap=Object.fromEntries(machines.map(row=>[row.id,row]));
  const rows=assignments.map(row=>{const order=orderMap[row.production_order_id]||{};return {...row,order,machine:machineMap[row.machine_id],line:lineMap[row.line_id],minutes:Math.max(30,(row.standard_minutes||0)-(row.actual_minutes||0))};});
  rows.sort((a,b)=>rule==='delivery'?dateValue(a.order.planned_end)-dateValue(b.order.planned_end):rule==='shortest'?a.minutes-b.minutes:rule==='value'?(b.planned_quantity||0)-(a.planned_quantity||0):(a.order.priority||3)-(b.order.priority||3));
  const cursors={};return rows.map((row,index)=>{const key=row.machine_id||`line-${row.line_id||index}`;let offset;if(mode==='infinite')offset=Math.max(0,Math.floor((dateValue(row.order.planned_start)-today.getTime())/DAY));else{offset=Math.floor((cursors[key]||0)/480);cursors[key]=(cursors[key]||0)+row.minutes;}const duration=Math.max(.2,row.minutes/480),endOffset=offset+duration,due=dateValue(row.order.planned_end),end=today.getTime()+endOffset*DAY;return {...row,offset,duration,endOffset,overload:endOffset>horizon,late:Boolean(due&&end>due),resource:key};});
}

function renderGantt(schedule,machines,horizon,today){const days=Array.from({length:horizon},(_,i)=>new Date(today.getTime()+i*DAY));const used=new Set(schedule.map(row=>row.machine_id));const rows=machines.filter(machine=>used.has(machine.id)||machines.length<=12);return `<div class="mcm-gantt mcm-timeline"><div class="mcm-resource-head">Recurso</div><div class="mcm-dates">${days.map((day,index)=>`<div class="${index===0?'today':''}"><b>${day.toLocaleDateString('pt-PT',{weekday:'short'})}</b><span>${day.toLocaleDateString('pt-PT',{day:'2-digit',month:'2-digit'})}</span></div>`).join('')}</div><div class="mcm-resources">${rows.map(machine=>{const tasks=schedule.filter(task=>task.machine_id===machine.id);return `<div class="mcm-resource-row" data-search="${esc(`${machine.code} ${machine.name} ${tasks.map(t=>t.order.order_no).join(' ')}`.toLowerCase())}"><div class="mcm-resource"><i class="${machine.status}"></i><b>${esc(machine.code)}</b><small>${esc(machine.name)}</small></div><div class="mcm-track" style="--days:${horizon}">${days.map((_,i)=>`<i class="${i===0?'today':''}"></i>`).join('')}${tasks.map((task,index)=>`<button class="mcm-task priority-${Math.min(5,task.order.priority||3)} ${task.late?'late':''} ${['maintenance','stopped'].includes(machine.status)?'conflict':''}" data-task="${task.id}" style="left:${task.offset/horizon*100}%;width:${Math.max(3,task.duration/horizon*100)}%;top:${7+(index%2)*24}px" title="${esc(task.order.order_no||'Ordem')} · ${number(task.minutes)} min"><b>${esc(task.order.order_no||`Tarefa ${task.id}`)}</b><span>${number(task.minutes)} min</span>${task.late||['maintenance','stopped'].includes(machine.status)?'<em>!</em>':''}</button>`).join('')}</div></div>`}).join('')||'<div class="empty">Sem tarefas atribuídas a máquinas.</div>'}</div></div>`;}

function alerts(capacity,schedule){const items=capacity.filter(row=>row.load_pct>85).sort((a,b)=>b.load_pct-a.load_pct).slice(0,2);const unavailable=schedule.find(row=>row.machine&&['maintenance','stopped'].includes(row.machine.status));if(unavailable)items.unshift({name:unavailable.machine.name,load_pct:101,required_minutes:unavailable.minutes,available_minutes:0,resource:true});if(!items.length)return '<div class="mcm-alert ok"><i>✓</i><div><b>Plano sem conflitos críticos</b><span>Capacidade, máquinas e filas estão equilibradas.</span></div></div>';return items.map(row=>`<div class="mcm-alert ${row.load_pct>100?'danger':'warning'}"><i>${row.load_pct>100?'!':'↑'}</i><div><b>${row.resource?'Recurso indisponível':'Estrangulamento detetado'} · ${esc(row.name)}</b><span>${row.resource?'A tarefa deve ser reafetada a uma máquina compatível.':`${percent(row.load_pct)} de carga · ${number(row.required_minutes-row.available_minutes)} min de diferença`}</span></div><a href="#/machines">Analisar →</a></div>`).join('');}
function scenarioCards(utilization,late,overloaded){return `<button data-scenario="priority"><span>Plano base</span><b>Prioridade</b><small>${utilization}% utilização · ${late} em risco</small><em>Aplicar cenário</em></button><button data-scenario="delivery"><span>Cenário A</span><b>Entrega primeiro</b><small>${Math.min(100,utilization+4)}% utilização · ${Math.max(0,late-1)} em risco</small><em>Aplicar cenário</em></button><button data-scenario="shortest"><span>Cenário B</span><b>Operações curtas</b><small>${Math.max(0,utilization-3)}% utilização · ${overloaded} conflitos</small><em>Aplicar cenário</em></button>`;}
function startDay(value){const date=new Date(value);date.setHours(0,0,0,0);return date;}
function dateValue(value){const time=value?new Date(value).getTime():0;return Number.isFinite(time)?time:0;}
