import { get } from '../api.js';
import { badge, esc, money, number, percent, progress } from '../format.js?v=20260819-5';
import { state } from '../state.js';
import { pageHeader } from '../ui.js?v=20260820-5';

export async function render(container){
  const [costs, employees, machines, downtime]=await Promise.all([get(`/reports/${state.companyId}/costs`),get(`/reports/${state.companyId}/employees`),get(`/reports/${state.companyId}/machines`),get(`/reports/${state.companyId}/downtime`)]);
  const total=costs.labor+costs.machines+costs.samples+costs.cutting;
  container.innerHTML=pageHeader('Análises de desempenho e custo','Resultados por colaborador, máquina e centro produtivo.')+`
    <div class="metric-grid"><div class="metric"><span class="label">Mão de obra direta</span><strong>${money(costs.labor)}</strong><span class="trend">${number(costs.production_good)} peças boas</span></div><div class="metric"><span class="label">Máquinas</span><strong>${money(costs.machines)}</strong></div><div class="metric"><span class="label">Amostras</span><strong>${money(costs.samples)}</strong></div><div class="metric"><span class="label">Corte</span><strong>${money(costs.cutting)}</strong></div><div class="metric"><span class="label">Total monitorizado</span><strong>${money(total)}</strong></div></div>
    <div class="card" style="margin-top:14px"><div class="card-header"><h2>Performance por funcionário</h2><span>Tempo-padrão ganho ÷ tempo real</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Código</th><th>Funcionário</th><th>Função</th><th>Peças boas</th><th>Rejeitadas</th><th>Horas</th><th>Eficiência</th><th>Custo M.O.</th><th>Custo/peça</th></tr></thead><tbody>${employees.map(row=>`<tr><td>${esc(row.code)}</td><td><b>${esc(row.name)}</b></td><td>${esc(row.job_title||'')}</td><td>${number(row.good)}</td><td>${number(row.rejected)}</td><td>${number(row.hours)}</td><td>${progress(row.efficiency,row.efficiency>=85?'green':'red')}</td><td>${money(row.labor_cost)}</td><td>${money(row.cost_per_good)}</td></tr>`).join('')}</tbody></table></div></div>
    <div class="card" style="margin-top:14px"><div class="card-header"><h2>Performance por máquina</h2><span>Produção, qualidade, utilização e custo</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Código</th><th>Máquina</th><th>Tipo</th><th>Estado</th><th>Produção</th><th>Horas</th><th>Performance</th><th>Qualidade</th><th>Custo</th><th>Custo/peça</th></tr></thead><tbody>${machines.map(row=>`<tr><td>${esc(row.code)}</td><td><b>${esc(row.name)}</b></td><td>${esc(row.type)}</td><td>${badge(row.status)}</td><td>${number(row.good)}</td><td>${number(row.hours)}</td><td>${percent(row.performance)}</td><td>${percent(row.quality)}</td><td>${money(row.cost)}</td><td>${money(row.cost_per_good)}</td></tr>`).join('')}</tbody></table></div></div>
    <div class="card" style="margin-top:14px"><div class="card-header"><h2>Paragens e OEE por linha</h2><span>Disponibilidade × Performance × Qualidade, a partir dos registos de paragem e produção</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Linha</th><th>Produtivos</th><th>Paragem</th><th>Disponibilidade</th><th>Performance</th><th>Qualidade</th><th>OEE</th></tr></thead><tbody>${downtime.lines.length?downtime.lines.map(row=>`<tr><td><b>${esc(row.name)}</b></td><td>${number(row.productive_minutes)} min</td><td>${number(row.downtime_minutes)} min</td><td>${percent(row.availability_pct)}</td><td>${percent(row.performance_pct)}</td><td>${percent(row.quality_pct)}</td><td>${progress(row.oee_pct,row.oee_pct>=65?'green':'red')}</td></tr>`).join(''):'<tr><td colspan="7" class="muted">Sem produção nem paragens registadas.</td></tr>'}</tbody></table></div>
    ${downtime.reasons.length?`<p class="muted" style="margin-top:10px">Motivos de paragem: ${downtime.reasons.map(row=>`${esc(row.label)} (${number(row.minutes)} min)`).join(' · ')}</p>`:''}</div>`;
}
