import { get } from '../api.js';
import { badge, esc, money, number, percent, progress } from '../format.js?v=20260819-5';
import { state } from '../state.js';
import { pageHeader } from '../ui.js?v=20260820-5';

export async function render(container){
  const results=await Promise.allSettled([get(`/reports/${state.companyId}/costs`),get(`/reports/${state.companyId}/employees`),get(`/reports/${state.companyId}/machines`),get(`/reports/${state.companyId}/downtime`),get(`/reports/${state.companyId}/operations-scorecard`)]);
  const value=(index,fallback)=>results[index].status==='fulfilled'?results[index].value:fallback;
  const costs=value(0,{labor:0,machines:0,samples:0,cutting:0,production_good:0});
  const employees=value(1,[]);
  const machines=value(2,[]);
  const downtime=value(3,{lines:[],reasons:[]});
  const score=value(4,{kpis:{}});
  const unavailable=results.filter(row=>row.status==='rejected').length;
  const total=costs.labor+costs.machines+costs.samples+costs.cutting;
  const k={otif_pct:0,orders_fulfilled:0,production_lead_days:0,first_pass_yield_pct:0,wip_orders:0,wip_age_days:0,actual_margin:0,rework_quantity:0,scrap_quantity:0,supplier_otd_pct:0,supplier_acceptance_pct:0,open_claim_count:0,finished_goods_quantity:0,...score.kpis};
  container.innerHTML=pageHeader('Análises de desempenho e custo','Resultados do ciclo completo, do prazo e qualidade à margem real.')+`
    ${unavailable?`<div class="page-inline-alert" role="status"><b>Dados parciais</b><span>${unavailable} área(s) não responderam. As restantes continuam disponíveis.</span></div>`:''}
    <div class="metric-grid"><div class="metric"><span class="label">OTIF</span><strong>${percent(k.otif_pct)}</strong><span class="trend">${number(k.orders_fulfilled)} encomendas completas</span></div><div class="metric"><span class="label">Lead time produtivo</span><strong>${number(k.production_lead_days)} dias</strong></div><div class="metric"><span class="label">First-pass yield</span><strong>${percent(k.first_pass_yield_pct)}</strong></div><div class="metric"><span class="label">WIP / idade média</span><strong>${number(k.wip_orders)} · ${number(k.wip_age_days)}d</strong></div><div class="metric"><span class="label">Margem real</span><strong>${money(k.actual_margin)}</strong></div></div>
    <div class="card section-spaced"><div class="card-header"><h2>Ciclo completo</h2><span>Qualidade, fornecedor, pós-venda e produto acabado</span></div><div class="metric-grid"><div class="metric"><span class="label">Retrabalho</span><strong>${number(k.rework_quantity)}</strong></div><div class="metric"><span class="label">Desperdício</span><strong>${number(k.scrap_quantity)}</strong></div><div class="metric"><span class="label">Fornecedor no prazo</span><strong>${percent(k.supplier_otd_pct)}</strong></div><div class="metric"><span class="label">Aceitação fornecedor</span><strong>${percent(k.supplier_acceptance_pct)}</strong></div><div class="metric"><span class="label">Reclamações abertas</span><strong>${number(k.open_claim_count)}</strong></div><div class="metric"><span class="label">Produto acabado</span><strong>${number(k.finished_goods_quantity)}</strong></div></div></div>
    <div class="metric-grid"><div class="metric"><span class="label">Mão de obra direta</span><strong>${money(costs.labor)}</strong><span class="trend">${number(costs.production_good)} peças boas</span></div><div class="metric"><span class="label">Máquinas</span><strong>${money(costs.machines)}</strong></div><div class="metric"><span class="label">Amostras</span><strong>${money(costs.samples)}</strong></div><div class="metric"><span class="label">Corte</span><strong>${money(costs.cutting)}</strong></div><div class="metric"><span class="label">Total monitorizado</span><strong>${money(total)}</strong></div></div>
    <div class="card section-spaced"><div class="card-header"><h2>Performance por funcionário</h2><span>Tempo-padrão ganho ÷ tempo real</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Código</th><th>Funcionário</th><th>Função</th><th>Peças boas</th><th>Rejeitadas</th><th>Horas</th><th>Eficiência</th><th>Custo M.O.</th><th>Custo/peça</th></tr></thead><tbody>${employees.map(row=>`<tr><td>${esc(row.code)}</td><td><b>${esc(row.name)}</b></td><td>${esc(row.job_title||'')}</td><td>${number(row.good)}</td><td>${number(row.rejected)}</td><td>${number(row.hours)}</td><td>${progress(row.efficiency,row.efficiency>=85?'green':'red')}</td><td>${money(row.labor_cost)}</td><td>${money(row.cost_per_good)}</td></tr>`).join('')}</tbody></table></div></div>
    <div class="card section-spaced"><div class="card-header"><h2>Performance por máquina</h2><span>Produção, qualidade, utilização e custo</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Código</th><th>Máquina</th><th>Tipo</th><th>Estado</th><th>Produção</th><th>Horas</th><th>Performance</th><th>Qualidade</th><th>Custo</th><th>Custo/peça</th></tr></thead><tbody>${machines.map(row=>`<tr><td>${esc(row.code)}</td><td><b>${esc(row.name)}</b></td><td>${esc(row.type)}</td><td>${badge(row.status)}</td><td>${number(row.good)}</td><td>${number(row.hours)}</td><td>${percent(row.performance)}</td><td>${percent(row.quality)}</td><td>${money(row.cost)}</td><td>${money(row.cost_per_good)}</td></tr>`).join('')}</tbody></table></div></div>
    <div class="card section-spaced"><div class="card-header"><h2>Paragens e OEE por linha</h2><span>Disponibilidade × Performance × Qualidade, a partir dos registos de paragem e produção</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Linha</th><th>Produtivos</th><th>Paragem</th><th>Disponibilidade</th><th>Performance</th><th>Qualidade</th><th>OEE</th></tr></thead><tbody>${downtime.lines.length?downtime.lines.map(row=>`<tr><td><b>${esc(row.name)}</b></td><td>${number(row.productive_minutes)} min</td><td>${number(row.downtime_minutes)} min</td><td>${percent(row.availability_pct)}</td><td>${percent(row.performance_pct)}</td><td>${percent(row.quality_pct)}</td><td>${progress(row.oee_pct,row.oee_pct>=65?'green':'red')}</td></tr>`).join(''):'<tr><td colspan="7" class="muted">Sem produção nem paragens registadas.</td></tr>'}</tbody></table></div>
    ${downtime.reasons.length?`<p class="muted u-mt-3">Motivos de paragem: ${downtime.reasons.map(row=>`${esc(row.label)} (${number(row.minutes)} min)`).join(' · ')}</p>`:''}</div>`;
}
