import { crudList, crudUpdate, post } from '../api.js';
import { badge, date, esc, number } from '../format.js?v=20260819-5';
import { recordModal } from '../quick_create.js';
import { state } from '../state.js';
import { pageHeader, toast } from '../ui.js?v=20260820-5';

export async function render(container) {
  const [orders,lines]=await Promise.all([crudList('sales-orders',state.companyId,'limit=2000'),crudList('sales-order-lines',state.companyId,'limit=2000')]);
  const quantityByOrder=Object.fromEntries(orders.map(order=>[order.id,lines.filter(line=>line.sales_order_id===order.id).reduce((sum,line)=>sum+(line.quantity||0),0)]));
  const active=orders.filter(row=>!['cancelled'].includes(row.status));
  const ready=active.filter(row=>row.status==='ready');
  const preparing=active.filter(row=>['confirmed','in_production'].includes(row.status));
  const shipped=active.filter(row=>row.status==='shipped');
  container.innerHTML=pageHeader('Expedição','Preparação, validação e saída das encomendas de cliente.','<a class="btn" href="#/erp-docs">Documentos Primavera</a><a class="btn" href="#/inventory">Confirmar stock</a><a class="btn primary" href="#/orders">Ver encomendas</a>')+`
    <div class="shipping-kpis"><article><span>A preparar</span><strong>${preparing.length}</strong><small>encomendas em produção</small></article><article><span>Prontas</span><strong>${ready.length}</strong><small>aguardam confirmação de saída</small></article><article><span>Expedidas</span><strong>${shipped.length}</strong><small>histórico disponível</small></article><article><span>Próxima entrega</span><strong>${date(nextDelivery(active))}</strong><small>data confirmada ao cliente</small></article></div>
    <div class="shipping-board"><section class="card"><div class="card-header"><h2>Fila de expedição</h2><span>${ready.length+preparing.length} encomendas abertas</span></div><div class="shipping-list">${[...ready,...preparing].map(row=>`<article><div class="shipping-order"><i>${row.status==='ready'?'✓':'◷'}</i><div><b>${esc(row.order_no)}</b><small>${esc(row.customer_po||'Sem PO de cliente')} · ${number(quantityByOrder[row.id])} un.</small></div></div><div><span>Entrega</span><b>${date(row.delivery_date)}</b></div><div>${badge(row.status)}</div><button class="btn small ${row.status==='ready'?'primary':''}" data-shipping-order="${row.id}" data-action="${row.status==='ready'?'dispatch':'ready'}">${row.status==='ready'?'Confirmar saída':'Marcar pronta'}</button></article>`).join('')||'<div class="empty"><strong>Sem expedições pendentes</strong>As novas encomendas prontas aparecerão aqui.</div>'}</div></section><aside class="card shipping-check"><div class="card-header"><h2>Checklist obrigatória</h2><span>Validada na saída</span></div><label><i>1</i> Quantidades e variantes conferidas</label><label><i>2</i> Controlo de qualidade concluído</label><label><i>3</i> Documento de expedição preparado</label><label><i>4</i> Transportador e volumes confirmados</label><div class="shipping-tip"><b>Primavera</b><p>A saída cria a guia na fila. Faturas, NC e ND saem em Documentos Primavera, com um clique.</p></div></aside></div>`;
  container.querySelectorAll('[data-shipping-order]').forEach(button=>button.addEventListener('click',async()=>{const row=orders.find(item=>item.id===Number(button.dataset.shippingOrder));if(button.dataset.action==='dispatch'){openDispatch(row,quantityByOrder[row.id],container);return;}try{await crudUpdate('sales-orders',row.id,{...row,status:'ready',company_id:state.companyId});toast('Encomenda marcada como pronta.');await render(container);}catch(error){toast(error.message,'error');}}));
}

function openDispatch(order,quantity,container){const local=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16);recordModal({title:`Confirmar saída · ${order.order_no}`,values:{shipment_no:`EXP-${order.order_no}`,quantity,shipped_at:local,quantities_checked:false,quality_checked:false,documents_checked:false,carrier_checked:false},fields:[{key:'shipment_no',label:'Documento de expedição',required:true,section:'Transporte'},{key:'carrier',label:'Transportador',required:true,section:'Transporte'},{key:'tracking_no',label:'Referência / tracking',section:'Transporte'},{key:'destination',label:'Destino',type:'textarea',section:'Transporte'},{key:'quantity',label:'Quantidade',type:'number',required:true,section:'Saída'},{key:'shipped_at',label:'Data e hora',type:'datetime-local',required:true,section:'Saída'},{key:'quantities_checked',label:'Quantidades e variantes conferidas',type:'checkbox',section:'Checklist'},{key:'quality_checked',label:'Qualidade concluída',type:'checkbox',section:'Checklist'},{key:'documents_checked',label:'Documentação preparada',type:'checkbox',section:'Checklist'},{key:'carrier_checked',label:'Transportador e volumes confirmados',type:'checkbox',section:'Checklist'}],save:payload=>post(`/production/sales-orders/${order.id}/dispatch`,payload),onSaved:()=>render(container)});}

function nextDelivery(rows){return rows.map(row=>row.delivery_date).filter(Boolean).sort()[0]||null;}
