import { crudList } from '../api.js';
import { renderEntityPage } from '../entity.js?v=20260826-3';
import { badge, date, esc, number, percent } from '../format.js?v=20260826-3';
import { state } from '../state.js';

const opts = (rows, label) => rows.map(row=>({value:row.id,label:label(row)}));

export async function renderConfectionTable(container, key) {
  const [allLines, shifts, employees, machines, operations, orders, styles, suppliers, batches, departments] = await Promise.all([
    'production-lines','work-shifts','employees','machines','operations','production-orders','styles','suppliers','batches','departments'
  ].map(resource=>crudList(resource,state.companyId,'limit=2000')));
  const departmentMap = Object.fromEntries(departments.map(row=>[row.id,row]));
  const sewingLines = allLines.filter(row=>{const department=departmentMap[row.department_id];return ['CONF','ACAB'].includes(department?.code)||department?.name?.toLowerCase().includes('confe');});
  const lines = sewingLines.length ? sewingLines : allLines;
  const index = rows => Object.fromEntries(rows.map(row=>[row.id,row]));
  const maps = {lines:index(allLines),shifts:index(shifts),employees:index(employees),machines:index(machines),operations:index(operations),orders:index(orders),styles:index(styles),suppliers:index(suppliers),batches:index(batches)};
  const configs = {
    days:{resource:'capacity-days',query:'sort=work_date&direction=asc',title:'Calendário diário de capacidade',subtitle:'Pessoas, ausências, pausas, setup, manutenção e eficiência por linha e turno.',singular:'dia de capacidade',newLabel:'Novo dia',fields:[
      {key:'work_date',label:'Data',type:'date',required:true,section:'Calendário'},{key:'line_id',label:'Linha / célula',type:'select',required:true,options:opts(lines,r=>r.name),section:'Calendário'},{key:'shift_id',label:'Turno',type:'select',required:true,options:opts(shifts,r=>r.name),section:'Calendário'},
      {key:'scheduled_employees',label:'Pessoas previstas',type:'number',required:true,default:0,section:'Pessoas'},{key:'absent_employees',label:'Ausências',type:'number',default:0,section:'Pessoas'},{key:'minutes_per_employee',label:'Minutos por pessoa',type:'number',default:480,section:'Tempo disponível'},{key:'break_minutes',label:'Pausa por pessoa',type:'number',default:30,section:'Tempo disponível'},
      {key:'setup_minutes',label:'Setup total (min)',type:'number',default:0,section:'Perdas planeadas'},{key:'maintenance_minutes',label:'Manutenção (min)',type:'number',default:0,section:'Perdas planeadas'},{key:'efficiency_pct',label:'Eficiência prevista (%)',type:'number',default:85,section:'Eficiência'},{key:'locked',label:'Fixar eficiência',type:'checkbox',help:'Não substituir pela eficiência histórica',section:'Eficiência'},{key:'notes',label:'Notas',type:'textarea',full:true,section:'Observações'},
    ],columns:[{key:'work_date',label:'Data',render:r=>date(r.work_date)},{key:'line_id',label:'Linha',render:r=>esc(maps.lines[r.line_id]?.name||'—')},{key:'shift_id',label:'Turno',render:r=>esc(maps.shifts[r.shift_id]?.name||'—')},{key:'scheduled_employees',label:'Previstos',render:r=>number(r.scheduled_employees)},{key:'absent_employees',label:'Ausentes',render:r=>number(r.absent_employees)},{key:'minutes_per_employee',label:'Min/pessoa',render:r=>number(r.minutes_per_employee)},{key:'setup_minutes',label:'Setup',render:r=>number(r.setup_minutes)},{key:'maintenance_minutes',label:'Manutenção',render:r=>number(r.maintenance_minutes)},{key:'efficiency_pct',label:'Eficiência',render:r=>percent(r.efficiency_pct)},{key:'locked',label:'Origem',render:r=>badge(r.locked?'fixa':'adaptativa')}]},
    shifts:{resource:'work-shifts',title:'Turnos de confeção',subtitle:'Horários, pausas e dias ativos; podem existir vários turnos por linha e dia.',singular:'turno',newLabel:'Novo turno',fields:[
      {key:'code',label:'Código',required:true},{key:'name',label:'Nome',required:true},{key:'start_time',label:'Início',required:true,default:'08:00'},{key:'end_time',label:'Fim',required:true,default:'17:00'},{key:'minutes_day',label:'Minutos brutos/dia',type:'number',default:480},{key:'break_minutes',label:'Pausas (min)',type:'number',default:30},{key:'weekdays',label:'Dias da semana (1=segunda)',type:'json',default:[1,2,3,4,5],full:true},{key:'active',label:'Estado',type:'checkbox',default:true,help:'Turno ativo'},
    ],columns:[{key:'code',label:'Código'},{key:'name',label:'Turno'},{key:'start_time',label:'Início'},{key:'end_time',label:'Fim'},{key:'minutes_day',label:'Minutos',render:r=>number(r.minutes_day)},{key:'break_minutes',label:'Pausas',render:r=>number(r.break_minutes)},{key:'weekdays',label:'Dias',render:r=>(r.weekdays||[]).join(', ')},{key:'active',label:'Estado',render:r=>badge(r.active?'ativo':'inativo')}]},
    events:{resource:'capacity-events',query:'sort=event_date&direction=desc',title:'Exceções e alterações de capacidade',subtitle:'Férias, faltas, formação, reuniões, manutenção, feriados e horas extra.',singular:'evento de capacidade',newLabel:'Novo evento',fields:[
      {key:'event_date',label:'Data',type:'date',required:true},{key:'event_type',label:'Tipo',type:'select',required:true,options:['absence','holiday','vacation','training','meeting','maintenance','overtime','other']},{key:'description',label:'Descrição',required:true},{key:'line_id',label:'Linha',type:'select',options:opts(lines,r=>r.name)},{key:'employee_id',label:'Funcionário',type:'select',options:opts(employees,r=>r.name)},{key:'machine_id',label:'Máquina',type:'select',options:opts(machines,r=>r.name)},{key:'minutes_delta',label:'Impacto em minutos',type:'number',default:0,help:'Negativo reduz capacidade; positivo acrescenta.'},{key:'status',label:'Estado',type:'select',options:['planned','confirmed','cancelled'],default:'confirmed'},{key:'notes',label:'Notas',type:'textarea',full:true},
    ],columns:[{key:'event_date',label:'Data',render:r=>date(r.event_date)},{key:'event_type',label:'Tipo',render:r=>badge(r.event_type)},{key:'description',label:'Descrição'},{key:'line_id',label:'Linha',render:r=>esc(maps.lines[r.line_id]?.name||'Todas')},{key:'employee_id',label:'Pessoa',render:r=>esc(maps.employees[r.employee_id]?.name||'—')},{key:'machine_id',label:'Máquina',render:r=>esc(maps.machines[r.machine_id]?.name||'—')},{key:'minutes_delta',label:'Impacto',render:r=>`${number(r.minutes_delta)} min`},{key:'status',label:'Estado',render:r=>badge(r.status)}]},
    skills:{resource:'skill-types',title:'Competências',subtitle:'Lista editável. Nas pessoas escolhe-se daqui, em vez de escrever à mão.',singular:'competência',newLabel:'Nova competência',fields:[
      {key:'code',label:'Código',required:true},{key:'name',label:'Nome',required:true},{key:'machine_type',label:'Tipo de máquina'},{key:'active',label:'Ativa',type:'checkbox',default:true},
    ],columns:[{key:'code',label:'Código'},{key:'name',label:'Competência'},{key:'machine_type',label:'Máquina'},{key:'active',label:'Estado',render:r=>badge(r.active?'ativa':'inativa')}]},
    machineTypes:{resource:'machine-types',title:'Tipos de máquina',subtitle:'Catálogo da casa. Nas máquinas escolhe-se daqui.',singular:'tipo',newLabel:'Novo tipo',fields:[
      {key:'code',label:'Código',required:true},{key:'name',label:'Nome',required:true},{key:'active',label:'Ativo',type:'checkbox',default:true},
    ],columns:[{key:'code',label:'Código'},{key:'name',label:'Tipo'},{key:'active',label:'Estado',render:r=>badge(r.active?'ativo':'inativo')}]},
    lines:{resource:'production-lines',query:[departments.find(row=>row.code==='CONF')?`department_id=${departments.find(row=>row.code==='CONF').id}`:'','active=true'].filter(Boolean).join('&'),title:'Linhas de produção',subtitle:'As mesmas linhas que aparecem no mapa. Uma linha nova aqui entra logo no plano.',singular:'linha',newLabel:'Nova linha',transform:payload=>{
      const conf = departments.find(row=>row.code==='CONF');
      return {...payload, department_id: payload.department_id || conf?.id, active: payload.active !== false};
    },fields:async()=>[
      {key:'code',label:'Código',required:true},{key:'name',label:'Nome',required:true},{key:'department_id',label:'Departamento',type:'select',options:opts(departments,r=>r.name),default:departments.find(row=>row.code==='CONF')?.id},
      {key:'production_mode',label:'Modo',type:'select',options:['line','cell','batch','piece'],default:'line'},
      {key:'capacity_minutes_day',label:'Minutos disponíveis/dia',type:'number',default:480,help:'Pessoas × minutos do turno. Ex.: 10 pessoas × 480 = 4800.'},
      {key:'target_pcs_hour',label:'Peças/hora',type:'number',default:0,help:'Ritmo da linha. Quantidade que consegue sair numa hora.'},
      {key:'target_efficiency',label:'Eficiência objetivo (%)',type:'number',default:85},{key:'active',label:'Ativa',type:'checkbox',default:true},
    ],columns:[{key:'code',label:'Código'},{key:'name',label:'Linha'},{key:'production_mode',label:'Modo',render:r=>badge(r.production_mode)},{key:'capacity_minutes_day',label:'Min/dia',render:r=>number(r.capacity_minutes_day)},{key:'target_pcs_hour',label:'Peças/h',render:r=>number(r.target_pcs_hour)},{key:'target_efficiency',label:'Eficiência',render:r=>percent(r.target_efficiency)},{key:'active',label:'Estado',render:r=>badge(r.active?'ativa':'inativa')}]},
    contractors:{resource:'suppliers',query:'supplier_type=sewing',title:'Confeçionadores',subtitle:'Casas a quem mandamos confeção. O trabalho a feitio (cliente traz-nos o serviço) planeia-se nas nossas linhas, não aqui.',singular:'confeçionador',newLabel:'Novo confeçionador',transform:payload=>({...payload,supplier_type:'sewing'}),fields:[
      {key:'code',label:'Código',required:true},{key:'name',label:'Nome',required:true},{key:'contact_name',label:'Contacto'},{key:'phone',label:'Telefone'},{key:'email',label:'Email'},
      {key:'weekly_capacity',label:'Peças/semana',type:'number',default:0,help:'O que este confeçionador aguenta por semana.'},{key:'piece_cost',label:'Custo por peça (€)',type:'number',default:0},
      {key:'lead_time_days',label:'Prazo (dias)',type:'number',default:7},{key:'city',label:'Localidade'},{key:'notes',label:'Notas',type:'textarea',full:true},{key:'active',label:'Ativo',type:'checkbox',default:true},
    ],columns:[{key:'code',label:'Código'},{key:'name',label:'Confeçionador'},{key:'weekly_capacity',label:'Peças/semana',render:r=>number(r.weekly_capacity)},{key:'piece_cost',label:'€/peça',render:r=>`${number(r.piece_cost)} €`},{key:'lead_time_days',label:'Prazo',render:r=>`${number(r.lead_time_days)} d`},{key:'city',label:'Localidade'},{key:'active',label:'Estado',render:r=>badge(r.active?'ativo':'inativo')}]},
    plans:{resource:'sewing-plans',query:'sort=start_date&direction=asc',title:'Plano de confeção',subtitle:'Produção própria, para terceiros, provável ou externa, sempre a consumir a capacidade correta.',singular:'ocupação',newLabel:'Nova ocupação',fields:[
      {key:'code',label:'Código do plano',required:true,section:'Identificação'},{key:'production_order_id',label:'Ordem de fabrico',type:'select',options:opts(orders,r=>r.order_no),section:'Identificação'},{key:'style_id',label:'Artigo',type:'select',options:opts(styles,r=>`${r.reference} · ${r.description}`),section:'Identificação'},{key:'source_type',label:'Origem',type:'select',options:['confirmed','forecast','third_party'],default:'confirmed',section:'Tipo de carga'},{key:'allocation_type',label:'Execução',type:'select',options:['internal','external'],default:'internal',section:'Tipo de carga'},
      {key:'line_id',label:'Linha interna',type:'select',options:opts(lines,r=>r.name),section:'Destino'},{key:'supplier_id',label:'Confeção externa',type:'select',options:opts(suppliers.filter(r=>r.supplier_type==='sewing'),r=>r.name),section:'Destino'},{key:'start_date',label:'Início',type:'date',required:true,section:'Calendário'},{key:'end_date',label:'Fim',type:'date',required:true,section:'Calendário'},{key:'quantity',label:'Quantidade',type:'number',default:0,help:'Com uma OF, 0 usa automaticamente a quantidade restante.',section:'Carga'},{key:'sam_minutes',label:'SAM por peça',type:'number',default:0,help:'Com um artigo ou OF, 0 lê automaticamente a gama operatória.',section:'Carga'},{key:'efficiency_pct',label:'Eficiência prevista (%)',type:'number',default:85,section:'Carga'},{key:'probability_pct',label:'Probabilidade (%)',type:'number',default:100,section:'Carga'},{key:'priority',label:'Prioridade',type:'number',default:3,section:'Controlo'},{key:'status',label:'Estado',type:'select',options:['planned','released','in_progress','paused','completed','cancelled'],default:'planned',section:'Controlo'},{key:'notes',label:'Notas',type:'textarea',full:true,section:'Observações'},
    ],columns:[{key:'code',label:'Plano',render:r=>`<b>${esc(r.code)}</b>`},{key:'production_order_id',label:'OF',render:r=>esc(maps.orders[r.production_order_id]?.order_no||'—')},{key:'style_id',label:'Artigo',render:r=>esc(maps.styles[r.style_id]?.reference||'—')},{key:'source_type',label:'Origem',render:r=>badge(r.source_type)},{key:'allocation_type',label:'Execução',render:r=>badge(r.allocation_type)},{key:'line_id',label:'Linha / externo',render:r=>esc(maps.lines[r.line_id]?.name||maps.suppliers[r.supplier_id]?.name||'Por atribuir')},{key:'start_date',label:'Início',render:r=>date(r.start_date)},{key:'end_date',label:'Fim',render:r=>date(r.end_date)},{key:'quantity',label:'Qtd.',render:r=>number(r.quantity)},{key:'sam_minutes',label:'SAM',render:r=>number(r.sam_minutes)},{key:'required_minutes',label:'Necessidade',render:r=>`${number(r.required_minutes)} min`},{key:'status',label:'Estado',render:r=>badge(r.status)}]},
    external:{resource:'external-capacities',query:'sort=week_start&direction=asc',title:'Capacidade externa',subtitle:'Disponibilidade semanal acordada com cada confeção externa.',singular:'capacidade externa',newLabel:'Nova capacidade',fields:[
      {key:'supplier_id',label:'Confeção externa',type:'select',required:true,options:opts(suppliers.filter(r=>r.supplier_type==='sewing'),r=>r.name)},{key:'week_start',label:'Início da semana',type:'date',required:true},{key:'capacity_units',label:'Capacidade oferecida',type:'number',required:true},{key:'reserved_units',label:'Já reservada',type:'number',default:0},{key:'unit_cost',label:'Custo por peça',type:'number',default:0},{key:'lead_time_days',label:'Lead time (dias)',type:'number',default:0},{key:'reliability_pct',label:'Fiabilidade (%)',type:'number',default:85},{key:'status',label:'Estado',type:'select',options:['available','limited','unavailable'],default:'available'},{key:'notes',label:'Notas',type:'textarea',full:true},
    ],columns:[{key:'supplier_id',label:'Fornecedor',render:r=>esc(maps.suppliers[r.supplier_id]?.name||'—')},{key:'week_start',label:'Semana',render:r=>date(r.week_start)},{key:'capacity_units',label:'Capacidade',render:r=>number(r.capacity_units)},{key:'reserved_units',label:'Reservada',render:r=>number(r.reserved_units)},{key:'free',label:'Livre',render:r=>`<b>${number(Math.max(0,r.capacity_units-r.reserved_units))}</b>`},{key:'unit_cost',label:'Custo/peça',render:r=>`${number(r.unit_cost)} €`},{key:'lead_time_days',label:'Prazo',render:r=>`${number(r.lead_time_days)} dias`},{key:'reliability_pct',label:'Fiabilidade',render:r=>percent(r.reliability_pct)},{key:'status',label:'Estado',render:r=>badge(r.status)}]},
    execution:{resource:'work-assignments',title:'Execução real da confeção',subtitle:'Tarefas, pessoas, máquinas, tempos previstos e realizados por operação.',singular:'tarefa',newLabel:'Nova tarefa',fields:[
      {key:'production_order_id',label:'Ordem',type:'select',required:true,options:opts(orders,r=>r.order_no)},{key:'batch_id',label:'Lote',type:'select',options:opts(batches,r=>r.batch_no)},{key:'operation_id',label:'Operação',type:'select',required:true,options:opts(operations,r=>`${r.code} · ${r.name}`)},{key:'employee_id',label:'Funcionário',type:'select',options:opts(employees,r=>r.name)},{key:'machine_id',label:'Máquina',type:'select',options:opts(machines,r=>r.name)},{key:'line_id',label:'Linha',type:'select',options:opts(lines,r=>r.name)},{key:'planned_quantity',label:'Quantidade planeada',type:'number',required:true},{key:'completed_quantity',label:'Produzida',type:'number',default:0},{key:'rejected_quantity',label:'Rejeitada',type:'number',default:0},{key:'standard_minutes',label:'Minutos-padrão',type:'number',default:0},{key:'actual_minutes',label:'Minutos reais',type:'number',default:0},{key:'planned_start',label:'Início',type:'datetime-local'},{key:'planned_end',label:'Fim',type:'datetime-local'},{key:'status',label:'Estado',type:'select',options:['queued','in_progress','paused','completed'],default:'queued'},
    ],columns:[{key:'production_order_id',label:'OF',render:r=>esc(maps.orders[r.production_order_id]?.order_no||'—')},{key:'operation_id',label:'Operação',render:r=>esc(maps.operations[r.operation_id]?.name||'—')},{key:'employee_id',label:'Funcionário',render:r=>esc(maps.employees[r.employee_id]?.name||'Por atribuir')},{key:'machine_id',label:'Máquina',render:r=>esc(maps.machines[r.machine_id]?.name||'Manual')},{key:'line_id',label:'Linha',render:r=>esc(maps.lines[r.line_id]?.name||'—')},{key:'planned_quantity',label:'Planeado',render:r=>number(r.planned_quantity)},{key:'completed_quantity',label:'Produzido',render:r=>number(r.completed_quantity)},{key:'rejected_quantity',label:'Rejeitado',render:r=>number(r.rejected_quantity)},{key:'standard_minutes',label:'Padrão',render:r=>number(r.standard_minutes)},{key:'actual_minutes',label:'Real',render:r=>number(r.actual_minutes)},{key:'status',label:'Estado',render:r=>badge(r.status)}]},
  };
  await renderEntityPage(container, configs[key] || configs.lines);
}
